# This modification is heavily based on GitHub user zonca's version linked
#  in https://github.com/openjournals/joss/issues/132#issuecomment-890440692

# The overall name of this action
name: Compile draft DAXA JOSS Paper

# Triggers on a push to the master branch - as I've decided that the paper can live in master
on:
  push:
    branches:
      - master
      - paper/writeJOSSPaper
    paths:
      - paper/**

# This action only really does one job, using the JOSS paper action to compile the MarkDown into something
#  slightly more pretty
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: paper/paper.md
          args: '-k paper/paper.md'
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper/paper.pdf

#jobs:
#  paper:
#    runs-on: ubuntu-latest
#    # Names the job
#    name: Paper Draft
#    # Sets up the steps of the job, firstly we check out the master branch
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Build TeX and PDF
#        uses: openjournals/openjournals-draft-action@v.1.0
#        with:
#          journal: joss
#          args: '-k paper/paper.md'
#        # Sets the specific journal to be built for, and where the Markdown file lives
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: paper
#          path: paper/
